"""
PDF traffic analysis report generator — green accent theme with chart visualizations.
"""
from __future__ import annotations
import logging, math, tempfile, shutil
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional
from fpdf import FPDF

logger = logging.getLogger(__name__)

# ── Green accent palette ──────────────────────────────────────────
_G = (21, 128, 61)
_GL = (34, 197, 94)
_GBG = (240, 253, 244)
_DARK = (17, 24, 39)
_MED = (75, 85, 99)
_LIGHT = (156, 163, 175)
_WHITE = (255, 255, 255)
_BORDER = (229, 231, 235)
_ALT = (240, 253, 244)

def _find_col(row, prefix, fallback=""):
    for k in row:
        if k.startswith(prefix): return k
    return fallback

def _detect_units(fieldnames):
    cal = any("m_per_s" in f for f in fieldnames)
    if cal:
        return dict(speed_col_prefix="avg_speed_m_per_s", dist_col_prefix="total_distance_m",
                    speed_label="m/s", dist_label="m", accel_label="m/s2",
                    inst_speed_prefix="inst_speed_m_per_s", is_calibrated=True)
    return dict(speed_col_prefix="avg_speed_px_per_s", dist_col_prefix="total_distance_px",
                speed_label="px/s", dist_label="px", accel_label="px/s2",
                inst_speed_prefix="inst_speed_px_per_s", is_calibrated=False)

def _gf(row, prefix, default=0.0):
    col = _find_col(row, prefix)
    if not col: return default
    try: return float(row[col])
    except: return default

def _count_samples(row):
    n = 0
    while True:
        found = False
        for k in row:
            if k.startswith(f"t{n}_x"):
                if row[k] not in ("", None): found = True
                break
        if not found: break
        n += 1
    return n


class TrafficReportPDF(FPDF):
    def header(self):
        self.set_fill_color(*_G)
        self.rect(0, 0, 210, 3.5, "F")
        self.set_y(7)
        
        logo_path = Path(__file__).resolve().parent.parent.parent / "static" / "logo.png"
        if logo_path.exists():
            self.image(str(logo_path), 10, 6, 9)
            self.set_x(22)
            
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(*_DARK)
        self.cell(0, 8, "ViTTA - Traffic Analysis Report", align="L")
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*_LIGHT)
        self.cell(0, 8, datetime.now().strftime("%Y-%m-%d %H:%M"), align="R")
        self.ln(12)
        self.set_draw_color(*_G)
        self.set_line_width(0.4)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*_LIGHT)
        self.cell(0, 8, f"Page {self.page_no()}/{{nb}} - Generated by ViTTA", align="C")

    def section_title(self, title):
        self.ln(2)
        y = self.get_y()
        self.set_fill_color(*_G)
        self.rect(10, y + 2, 3, 3, "F")
        self.set_x(16)
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(*_DARK)
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*_G)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 70, self.get_y())
        self.ln(3)

    def kv_row(self, key, value):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*_MED)
        self.cell(60, 6, key, new_x="RIGHT")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*_DARK)
        self.cell(0, 6, str(value), new_x="LMARGIN", new_y="NEXT")

    def summary_card(self, items):
        n = len(items)
        if n == 0: return
        card_w = min(45, 190 // n)
        gap = 3
        total_w = n * card_w + (n - 1) * gap
        start_x = 10 + (190 - total_w) / 2
        y = self.get_y()
        for i, (label, value) in enumerate(items):
            x = start_x + i * (card_w + gap)
            self.set_fill_color(*_GBG)
            self.set_draw_color(*_BORDER)
            self.rect(x, y, card_w, 18, "DF")
            self.set_fill_color(*_G)
            self.rect(x, y, card_w, 2, "F")
            self.set_xy(x, y + 3)
            self.set_font("Helvetica", "B", 11)
            self.set_text_color(*_DARK)
            self.cell(card_w, 6, str(value), align="C")
            self.set_xy(x, y + 10)
            self.set_font("Helvetica", "", 6.5)
            self.set_text_color(*_MED)
            self.cell(card_w, 5, label, align="C")
        self.set_y(y + 22)

    def styled_table(self, headers, rows, col_widths=None):
        n = len(headers)
        if col_widths is None:
            w = 190 // n
            col_widths = [w] * n
            for i in range(190 - sum(col_widths)):
                col_widths[i] += 1
        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(*_G)
        self.set_text_color(*_WHITE)
        for i, h in enumerate(headers):
            self.cell(col_widths[i], 7, h, border=0, align="C", fill=True)
        self.ln()
        self.set_font("Helvetica", "", 8)
        for ri, row in enumerate(rows):
            self.set_fill_color(*(_ALT if ri % 2 == 0 else _WHITE))
            self.set_text_color(*_DARK)
            for i, val in enumerate(row):
                self.cell(col_widths[i], 6, str(val), border=0, align="C", fill=True)
            self.ln()
        self.set_draw_color(*_BORDER)
        self.set_line_width(0.2)
        self.line(10, self.get_y(), 200, self.get_y())


def generate_report(csv_data, output_path, metadata=None, job_stats=None):
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    pdf = TrafficReportPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    fieldnames = list(csv_data[0].keys()) if csv_data else []
    units = _detect_units(fieldnames)
    spd_label, dist_label = units["speed_label"], units["dist_label"]

    # ── Parse all data ────────────────────────────────────────────
    total_vehicles = len(csv_data)
    avg_speeds, durations = [], []
    max_speed_overall = 0.0
    class_counts = defaultdict(int)
    direction_counts = defaultdict(int)
    behaviour_counts = defaultdict(int)
    speed_by_class = defaultdict(list)
    dist_by_class = defaultdict(list)
    all_lin, all_lat, all_headways = [], [], []
    vehicle_intervals = []

    lin_pf = "accel_linear_m_per_s2" if units["is_calibrated"] else "accel_linear_px_per_s2"
    lat_pf = "accel_lateral_m_per_s2" if units["is_calibrated"] else "accel_lateral_px_per_s2"

    for row in csv_data:
        cls = row.get("class_name", "Unknown")
        class_counts[cls] += 1
        direction_counts[row.get("direction", "Unknown")] += 1
        behaviour_counts[row.get("behavior_class", "Unknown")] += 1
        s = _gf(row, units["speed_col_prefix"])
        if s > 0:
            avg_speeds.append(s)
            max_speed_overall = max(max_speed_overall, s)
            speed_by_class[cls].append(s)
        d = _gf(row, units["dist_col_prefix"])
        if d > 0:
            dist_by_class[cls].append(d)
        ns = _count_samples(row)
        try: t_first = float(row.get("timestamp_first_seen", 0))
        except: t_first = 0.0
        t_last = t_first + max(0, ns - 1) * 0.5
        vehicle_intervals.append((t_first, t_last))
        dur = max(0, ns - 1) * 0.5
        if dur > 0: durations.append(dur)
        for i in range(ns):
            la = _gf(row, f"t{i}_{lin_pf}")
            ll = _gf(row, f"t{i}_{lat_pf}")
            if la != 0: all_lin.append(la)
            if ll != 0: all_lat.append(ll)
            hw = _gf(row, f"t{i}_time_headway_s")
            if 0 < hw < 120: all_headways.append(hw)
            inst = _gf(row, f"t{i}_{units['inst_speed_prefix']}")
            max_speed_overall = max(max_speed_overall, inst)

    total_time = (max(t[1] for t in vehicle_intervals) - min(t[0] for t in vehicle_intervals)) if vehicle_intervals else 1
    avg_speed = sum(avg_speeds) / len(avg_speeds) if avg_speeds else 0
    avg_duration = sum(durations) / len(durations) if durations else 0
    density = total_vehicles / (total_time / 60) if total_time > 0 else 0

    # ══════════════════════════════════════════════════════════════
    # Section 1: Summary Cards
    # ══════════════════════════════════════════════════════════════
    pdf.summary_card([
        ("Total Vehicles", str(total_vehicles)),
        (f"Avg Speed ({spd_label})", f"{avg_speed:.1f}"),
        (f"Peak Speed ({spd_label})", f"{max_speed_overall:.1f}"),
        ("Avg Duration (s)", f"{avg_duration:.1f}"),
    ])
    pdf.summary_card([
        ("Density (veh/min)", f"{density:.1f}"),
        ("Analysis Time (s)", f"{total_time:.1f}"),
        ("Avg Headway (s)", f"{sum(all_headways)/len(all_headways):.1f}" if all_headways else "N/A"),
        ("Vehicle Classes", str(len(class_counts))),
    ])
    pdf.ln(4)

    # ══════════════════════════════════════════════════════════════
    # Section 2: Video & Processing Info
    # ══════════════════════════════════════════════════════════════
    pdf.section_title("1. Video & Processing Information")
    meta = metadata or {}
    for k, v in meta.items():
        pdf.kv_row(str(k), str(v))
    if job_stats:
        pdf.kv_row("Processing Time", f"{job_stats.get('elapsed_sec',0):.1f} seconds")
        pdf.kv_row("Frames Processed", str(job_stats.get("processed_frames", "N/A")))
        pdf.kv_row("Vehicles Tracked", str(job_stats.get("csv_rows", "N/A")))
        if job_stats.get("pixels_per_metre"):
            pdf.kv_row("Calibration", f"{job_stats['pixels_per_metre']:.2f} px/m")
        pdf.kv_row("Units", "Metres (calibrated)" if units["is_calibrated"] else "Pixels (uncalibrated)")
    pdf.ln(4)

    # ══════════════════════════════════════════════════════════════
    # Section 3: Summary Statistics
    # ══════════════════════════════════════════════════════════════
    pdf.section_title("2. Summary Statistics")
    pdf.styled_table(["Metric", "Value"], [
        ["Total Vehicles Detected", str(total_vehicles)],
        [f"Avg Speed ({spd_label})", f"{avg_speed:.1f}"],
        [f"Peak Speed ({spd_label})", f"{max_speed_overall:.1f}"],
        ["Avg Track Duration (s)", f"{avg_duration:.1f}"],
        ["Traffic Density (veh/min)", f"{density:.1f}"],
        ["Total Analysis Duration (s)", f"{total_time:.1f}"],
    ], [95, 95])
    pdf.ln(6)

    # ══════════════════════════════════════════════════════════════
    # Section 4: Vehicle Composition
    # ══════════════════════════════════════════════════════════════
    pdf.section_title("3. Vehicle Composition")
    comp_rows = []
    for cls in sorted(class_counts.keys()):
        c = class_counts[cls]
        pct = c / total_vehicles * 100 if total_vehicles > 0 else 0
        comp_rows.append([cls, str(c), f"{pct:.1f}%"])
    comp_rows.append(["TOTAL", str(total_vehicles), "100.0%"])
    pdf.styled_table(["Vehicle Class", "Count", "Percentage"], comp_rows, [70, 50, 70])
    pdf.ln(6)

    # ══════════════════════════════════════════════════════════════
    # Section 5: Direction Breakdown
    # ══════════════════════════════════════════════════════════════
    pdf.section_title("4. Direction Breakdown")
    dir_rows = []
    for d in sorted(direction_counts.keys()):
        c = direction_counts[d]
        pct = c / total_vehicles * 100 if total_vehicles > 0 else 0
        dir_rows.append([d, str(c), f"{pct:.1f}%"])
    pdf.styled_table(["Direction", "Vehicles", "Percentage"], dir_rows, [70, 50, 70])
    pdf.ln(6)

    # ══════════════════════════════════════════════════════════════
    # Section 6: Speed by Class
    # ══════════════════════════════════════════════════════════════
    pdf.section_title(f"5. Speed Statistics by Vehicle Class")
    sp_rows = []
    for cls in sorted(speed_by_class.keys()):
        sp = speed_by_class[cls]
        sp_rows.append([cls, str(len(sp)), f"{sum(sp)/len(sp):.1f}", f"{min(sp):.1f}", f"{max(sp):.1f}"])
    pdf.styled_table(["Class", "Vehicles", f"Avg ({spd_label})", f"Min ({spd_label})", f"Max ({spd_label})"],
                     sp_rows, [40, 30, 40, 40, 40])
    pdf.ln(6)

    # ══════════════════════════════════════════════════════════════
    # Section 7: Distance
    # ══════════════════════════════════════════════════════════════
    if dist_by_class:
        pdf.section_title(f"6. Distance Analysis ({dist_label})")
        d_rows = []
        gt = 0.0
        for cls in sorted(dist_by_class.keys()):
            ds = dist_by_class[cls]
            t = sum(ds); gt += t
            d_rows.append([cls, str(len(ds)), f"{t/len(ds):.1f}", f"{t:.1f}", f"{max(ds):.1f}"])
        d_rows.append(["ALL", str(total_vehicles), "", f"{gt:.1f}", ""])
        pdf.styled_table(["Class", "Vehicles", f"Avg ({dist_label})", f"Total ({dist_label})", f"Max ({dist_label})"],
                        d_rows, [35, 30, 40, 45, 40])
        pdf.ln(6)

    # ══════════════════════════════════════════════════════════════
    # Section 8: Behaviour
    # ══════════════════════════════════════════════════════════════
    if behaviour_counts:
        pdf.section_title("7. Behaviour Classification")
        beh_rows = []
        for b in sorted(behaviour_counts.keys()):
            c = behaviour_counts[b]
            pct = c / total_vehicles * 100 if total_vehicles > 0 else 0
            beh_rows.append([b, str(c), f"{pct:.1f}%"])
        pdf.styled_table(["Behaviour", "Vehicles", "Percentage"], beh_rows, [70, 50, 70])
        pdf.ln(6)

    # ══════════════════════════════════════════════════════════════
    # Section 9: Acceleration
    # ══════════════════════════════════════════════════════════════
    al = units["accel_label"]
    if all_lin or all_lat:
        pdf.section_title(f"8. Acceleration Profile ({al})")
        import statistics
        def _s(vals):
            if not vals: return ["N/A"] * 5
            sv = sorted(vals)
            return [f"{sum(vals)/len(vals):.2f}", f"{min(vals):.2f}", f"{max(vals):.2f}",
                    f"{sv[int(len(sv)*0.05)]:.2f}" if len(sv) > 20 else f"{min(vals):.2f}",
                    f"{sv[int(len(sv)*0.95)]:.2f}" if len(sv) > 20 else f"{max(vals):.2f}"]
        ls, la = _s(all_lin), _s(all_lat)
        ac_rows = [["Mean", ls[0], la[0]], ["Min", ls[1], la[1]], ["Max", ls[2], la[2]],
                   ["P5", ls[3], la[3]], ["P95", ls[4], la[4]],
                   ["Samples", str(len(all_lin)), str(len(all_lat))]]
        pdf.styled_table(["Metric", "Linear (braking/accel)", "Lateral (steering)"],
                        ac_rows, [60, 65, 65])
        pdf.ln(6)

    # ══════════════════════════════════════════════════════════════
    # Section 10: Headway
    # ══════════════════════════════════════════════════════════════
    if all_headways:
        pdf.section_title("9. Headway & Safety Analysis")
        avg_hw = sum(all_headways) / len(all_headways)
        tg = sum(1 for h in all_headways if h < 1.2)
        cf = sum(1 for h in all_headways if 1.2 <= h < 2.0)
        sf = sum(1 for h in all_headways if h >= 2.0)
        th = len(all_headways)
        hw_rows = [
            ["Avg Time Headway (s)", f"{avg_hw:.2f}"],
            ["Min Time Headway (s)", f"{min(all_headways):.2f}"],
            ["Total Samples", str(th)],
            ["Tailgating (<1.2s)", f"{tg} ({tg/th*100:.1f}%)"],
            ["Close Following (1.2-2.0s)", f"{cf} ({cf/th*100:.1f}%)"],
            ["Safe Following (>=2.0s)", f"{sf} ({sf/th*100:.1f}%)"],
        ]
        pdf.styled_table(["Metric", "Value"], hw_rows, [95, 95])
        pdf.ln(6)

    # ══════════════════════════════════════════════════════════════
    # Section 11: Top 15 Longest Tracked
    # ══════════════════════════════════════════════════════════════
    if durations:
        pdf.section_title("10. Longest Tracked Vehicles (Top 15)")
        tracks = []
        for row in csv_data:
            ns = _count_samples(row)
            dur = max(0, ns - 1) * 0.5
            if dur > 0:
                tracks.append((row.get("track_id","?"), row.get("class_name","?"), dur,
                              _gf(row, units["speed_col_prefix"]),
                              _gf(row, units["dist_col_prefix"]), row.get("direction","?")))
        tracks.sort(key=lambda x: x[2], reverse=True)
        t_rows = [[str(t[0]), t[1], f"{t[2]:.1f}", f"{t[3]:.1f}", f"{t[4]:.1f}", t[5]] for t in tracks[:15]]
        pdf.styled_table(["ID", "Class", "Dur (s)", f"Speed ({spd_label})", f"Dist ({dist_label})", "Dir"],
                        t_rows, [20, 35, 30, 35, 35, 35])
        pdf.ln(6)

    # ══════════════════════════════════════════════════════════════
    # Section 12: Top 10 Fastest
    # ══════════════════════════════════════════════════════════════
    fast = []
    for row in csv_data:
        s = _gf(row, units["speed_col_prefix"])
        if s > 0:
            fast.append((row.get("track_id","?"), row.get("class_name","?"), s,
                        _gf(row, units["dist_col_prefix"]), row.get("behavior_class","?")))
    if fast:
        fast.sort(key=lambda x: x[2], reverse=True)
        pdf.section_title("11. Top 10 Fastest Vehicles")
        f_rows = [[str(t[0]), t[1], f"{t[2]:.1f}", f"{t[3]:.1f}", t[4]] for t in fast[:10]]
        pdf.styled_table(["ID", "Class", f"Avg Speed ({spd_label})", f"Distance ({dist_label})", "Behaviour"],
                        f_rows, [20, 35, 45, 45, 45])
        pdf.ln(6)

    # ══════════════════════════════════════════════════════════════
    # VISUALIZATIONS — appended at the end (same charts as dashboard)
    # ══════════════════════════════════════════════════════════════
    chart_dir = Path(tempfile.mkdtemp(prefix="vitta_charts_"))
    try:
        from vitta.export.pdf_charts import (
            chart_composition, chart_speed_hist,
            chart_direction, chart_behaviour,
            chart_class_speed, chart_density,
            chart_headway_hist, chart_speed_headway,
        )
        charts = {}
        # 1. Vehicle Composition (Donut)
        if class_counts:
            charts["comp"] = chart_composition(dict(class_counts), chart_dir)
        # 2. Speed Distribution (Histogram)
        if avg_speeds:
            charts["speed"] = chart_speed_hist(avg_speeds, spd_label, chart_dir)
        # 3. Direction Breakdown (Polar)
        if direction_counts:
            charts["dir"] = chart_direction(dict(direction_counts), chart_dir)
        # 4. Class Speed Comparison (Horizontal Bar)
        if speed_by_class:
            charts["cls_spd"] = chart_class_speed(dict(speed_by_class), spd_label, chart_dir)
        # 5. Behaviour Distribution (Horizontal Bar)
        if behaviour_counts:
            charts["beh"] = chart_behaviour(dict(behaviour_counts), chart_dir)
        # 6. Speed vs Headway (Scatter)
        scatter_speeds, scatter_headways, scatter_classes = [], [], []
        inst_pf = units["inst_speed_prefix"]
        for row in csv_data:
            vcls = row.get("class_name", "Unknown")
            ns = _count_samples(row)
            for i in range(ns):
                s = _gf(row, f"t{i}_{inst_pf}")
                h = _gf(row, f"t{i}_time_headway_s")
                if s > 0 and 0 < h < 60:
                    scatter_speeds.append(s)
                    scatter_headways.append(h)
                    scatter_classes.append(vcls)
        if scatter_speeds:
            charts["scatter"] = chart_speed_headway(
                scatter_speeds, scatter_headways, scatter_classes, spd_label, chart_dir)
        # 7. Traffic Density Over Time (Area)
        if vehicle_intervals:
            gs = int(min(t[0] for t in vehicle_intervals))
            ge = int(max(t[1] for t in vehicle_intervals)) + 1
            dl = list(range(gs, ge + 1))
            dv = [sum(1 for (ts, te) in vehicle_intervals if ts <= t + 1 and te >= t) for t in dl]
            charts["dens"] = chart_density(dl, dv, chart_dir)
        # 8. Headway Distribution (Histogram)
        if scatter_headways:
            charts["headway"] = chart_headway_hist(scatter_headways, chart_dir)

        if charts:
            pdf.add_page()
            pdf.set_font("Helvetica", "B", 16)
            pdf.set_text_color(*_DARK)
            pdf.cell(0, 10, "Visualizations", align="C", new_x="LMARGIN", new_y="NEXT")
            pdf.set_draw_color(*_G)
            pdf.set_line_width(0.5)
            y = pdf.get_y()
            pdf.line(60, y, 150, y)
            pdf.ln(6)

            # Helper: get rendered height (mm) for an image placed at a given width
            def _img_height_mm(img_path, target_w_mm=92):
                try:
                    from PIL import Image as PILImage
                    with PILImage.open(str(img_path)) as im:
                        w_px, h_px = im.size
                    return target_w_mm * h_px / w_px
                except Exception:
                    return 62  # safe fallback

            CHART_W = 92       # mm width for each chart
            PAIR_GAP = 6       # mm vertical gap between rows
            PAGE_H = 297       # A4 height
            MARGIN_B = 20      # bottom margin

            # Layout: two charts per row (same order as dashboard)
            pairs = [
                ("comp", "speed"),       # Composition + Speed Histogram
                ("dir", "cls_spd"),      # Direction + Class Speed
                ("beh", "scatter"),      # Behaviour + Speed vs Headway
                ("dens", "headway"),     # Density + Headway
            ]
            titles = {
                "comp": "Vehicle Composition",
                "speed": "Speed Distribution",
                "dir": "Direction Breakdown",
                "cls_spd": "Class Speed Comparison",
                "beh": "Behaviour Distribution",
                "scatter": "Speed vs Headway",
                "dens": "Traffic Density Over Time",
                "headway": "Headway Distribution"
            }
            for left_key, right_key in pairs:
                lp = charts.get(left_key)
                rp = charts.get(right_key)
                if not lp and not rp:
                    continue

                # Compute the max height of the pair
                lh = _img_height_mm(lp) if lp and Path(lp).exists() else 0
                rh = _img_height_mm(rp) if rp and Path(rp).exists() else 0
                row_h = max(lh, rh) + 8  # 8mm for title

                y = pdf.get_y()
                # Page break if the row won't fit
                if y + row_h + PAIR_GAP > PAGE_H - MARGIN_B:
                    pdf.add_page()
                    y = pdf.get_y()

                pdf.set_font("Helvetica", "B", 10)
                pdf.set_text_color(75, 85, 99)  # #4B5563
                if lp and Path(lp).exists():
                    pdf.set_xy(10, y)
                    pdf.cell(CHART_W, 6, titles.get(left_key, ""), align="C")
                    pdf.image(str(lp), x=10, y=y+6, w=CHART_W)
                if rp and Path(rp).exists():
                    pdf.set_xy(107, y)
                    pdf.cell(CHART_W, 6, titles.get(right_key, ""), align="C")
                    pdf.image(str(rp), x=107, y=y+6, w=CHART_W)
                pdf.set_y(y + row_h + PAIR_GAP)

    except Exception as e:
        logger.warning(f"Chart generation failed: {e}")
    finally:
        shutil.rmtree(chart_dir, ignore_errors=True)

    pdf.output(str(output_path))
    logger.info(f"PDF report saved: {output_path}")
    return output_path

